# Unitree G1 Multi-Camera Auto-Detection Configuration
# 自动检测多相机配置，支持1-4个相机的自动识别

### fps by manual
fps: 30

# 相机自动检测配置
camera_detection:
  auto_detect: true              # 启用自动检测
  file_pattern: "*.jpg"         # 图像文件模式
  camera_naming: "color_{idx}"  # 相机命名格式，{idx}会被替换为相机索引
  max_cameras: 4                # 最大支持相机数量

features:
  observation:
    # 图像配置将在运行时自动生成
    images: []  # 运行时自动填充：color_0, color_1, color_2, color_3等
    
    state:
      ### G1机器人状态配置：28维（4个肢体 × 7个关节）
      sub_state:
      - names: 
        - left_arm_joint_1_rad
        - left_arm_joint_2_rad
        - left_arm_joint_3_rad
        - left_arm_joint_4_rad
        - left_arm_joint_5_rad
        - left_arm_joint_6_rad
        - left_arm_joint_7_rad
        args:
          json_path: states.left_arm.qpos
          range_from: 0
          range_to: 7
      
      - names: 
        - right_arm_joint_1_rad
        - right_arm_joint_2_rad
        - right_arm_joint_3_rad
        - right_arm_joint_4_rad
        - right_arm_joint_5_rad
        - right_arm_joint_6_rad
        - right_arm_joint_7_rad
        args:
          json_path: states.right_arm.qpos
          range_from: 0
          range_to: 7

      - names: 
        - left_hand_joint_1_rad
        - left_hand_joint_2_rad
        - left_hand_joint_3_rad
        - left_hand_joint_4_rad
        - left_hand_joint_5_rad
        - left_hand_joint_6_rad
        - left_hand_joint_7_rad
        args:
          json_path: states.left_hand.qpos
          range_from: 0
          range_to: 7

      - names: 
        - right_hand_joint_1_rad
        - right_hand_joint_2_rad
        - right_hand_joint_3_rad
        - right_hand_joint_4_rad
        - right_hand_joint_5_rad
        - right_hand_joint_6_rad
        - right_hand_joint_7_rad
        args:
          json_path: states.right_hand.qpos
          range_from: 0
          range_to: 7

  action:
    ### G1机器人动作配置：28维（4个肢体 × 7个关节）
    timeline_offset: 1
    sub_action:
    - names: 
      - left_arm_joint_1_rad
      - left_arm_joint_2_rad
      - left_arm_joint_3_rad
      - left_arm_joint_4_rad
      - left_arm_joint_5_rad
      - left_arm_joint_6_rad
      - left_arm_joint_7_rad
      args:
        json_path: actions.left_arm.qpos
        range_from: 0
        range_to: 7
    
    - names: 
      - right_arm_joint_1_rad
      - right_arm_joint_2_rad
      - right_arm_joint_3_rad
      - right_arm_joint_4_rad
      - right_arm_joint_5_rad
      - right_arm_joint_6_rad
      - right_arm_joint_7_rad
      args:
        json_path: actions.right_arm.qpos
        range_from: 0
        range_to: 7

    - names: 
      - left_hand_joint_1_rad
      - left_hand_joint_2_rad
      - left_hand_joint_3_rad
      - left_hand_joint_4_rad
      - left_hand_joint_5_rad
      - left_hand_joint_6_rad
      - left_hand_joint_7_rad
      args:
        json_path: actions.left_hand.qpos
        range_from: 0
        range_to: 7

    - names: 
      - right_hand_joint_1_rad
      - right_hand_joint_2_rad
      - right_hand_joint_3_rad
      - right_hand_joint_4_rad
      - right_hand_joint_5_rad
      - right_hand_joint_6_rad
      - right_hand_joint_7_rad
      args:
        json_path: actions.right_hand.qpos
        range_from: 0
        range_to: 7
