### fps by manual - estimated from JSON metadata (bag_length_seconds)
fps: 30

features:
  observation:
    images:

    ### left head camera - compressed RGB image
    - cam_name: head_left_rgb
      args:
        topic_name: /hdas/camera_head/left_raw/image_raw_color/compressed
      # messages: sensor_msgs/msg/CompressedImage

    ### right head camera - compressed RGB image
    - cam_name: head_right_rgb
      args:
        topic_name: /hdas/camera_head/right_raw/image_raw_color/compressed
      # messages: sensor_msgs/msg/CompressedImage

    ### left wrist camera - compressed RGB image
    - cam_name: wrist_left_rgb
      args:
        topic_name: /hdas/camera_wrist_left/color/image_raw/compressed
      # messages: sensor_msgs/msg/CompressedImage

    ### right wrist camera - compressed RGB image
    - cam_name: wrist_right_rgb
      args:
        topic_name: /hdas/camera_wrist_right/color/image_raw/compressed
      # messages: sensor_msgs/msg/CompressedImage

    ### left wrist camera - depth image
    - cam_name: wrist_left_depth
      args:
        topic_name: /hdas/camera_wrist_left/aligned_depth_to_color/image_raw
      # messages: sensor_msgs/msg/Image

    ### right wrist camera - depth image
    - cam_name: wrist_right_depth
      args:
        topic_name: /hdas/camera_wrist_right/aligned_depth_to_color/image_raw
      # messages: sensor_msgs/msg/Image

    state:
      ### state data combination: left arm + right arm + left gripper + right gripper
      sub_state:

      ### left arm joint state (7 joints)
      - names: 
        - left_arm_joint_1
        - left_arm_joint_2
        - left_arm_joint_3
        - left_arm_joint_4
        - left_arm_joint_5
        - left_arm_joint_6
        - left_arm_joint_7
        args:
          topic_name: /hdas/feedback_arm_left
          range_from: 0
          range_to: 7
        # messages: sensor_msgs/msg/JointState

      ### right arm joint state (7 joints)
      - names: 
        - right_arm_joint_1
        - right_arm_joint_2
        - right_arm_joint_3
        - right_arm_joint_4
        - right_arm_joint_5
        - right_arm_joint_6
        - right_arm_joint_7
        args:
          topic_name: /hdas/feedback_arm_right
          range_from: 0
          range_to: 7
        # messages: sensor_msgs/msg/JointState

      ### left gripper state (1 joint)
      - names: 
        - left_gripper_position
        args:
          topic_name: /hdas/feedback_gripper_left
          range_from: 0
          range_to: 1
        # messages: sensor_msgs/msg/JointState

      ### right gripper state (1 joint)
      - names: 
        - right_gripper_position
        args:
          topic_name: /hdas/feedback_gripper_right
          range_from: 0
          range_to: 1
        # messages: sensor_msgs/msg/JointState

      ### torso state - multiple joints
      - names: 
        - torso_joint_1
        - torso_joint_2
        - torso_joint_3
        args:
          topic_name: /hdas/feedback_torso
          range_from: 0
          range_to: 3
        # messages: sensor_msgs/msg/JointState

      ### chassis state - wheels or mobile base
      - names: 
        - chassis_wheel_1
        - chassis_wheel_2
        - chassis_wheel_3
        - chassis_wheel_4
        args:
          topic_name: /hdas/feedback_chassis
          range_from: 0
          range_to: 4
        # messages: sensor_msgs/msg/JointState

      ### chassis IMU data - acceleration and angular velocity
      - names:
        - chassis_imu_accel_x
        - chassis_imu_accel_y
        - chassis_imu_accel_z
        - chassis_imu_gyro_x
        - chassis_imu_gyro_y
        - chassis_imu_gyro_z
        args:
          topic_name: /hdas/imu_chassis
          range_from: 0
          range_to: 6
        # messages: sensor_msgs/msg/Imu

      ### torso IMU data
      - names:
        - torso_imu_accel_x
        - torso_imu_accel_y
        - torso_imu_accel_z
        - torso_imu_gyro_x
        - torso_imu_gyro_y
        - torso_imu_gyro_z
        args:
          topic_name: /hdas/imu_torso
          range_from: 0
          range_to: 6
        # messages: sensor_msgs/msg/Imu

  action:
    ### action data: target joint state (time offset version of observation)
    timeline_offset: 1
    sub_action:

    ### left arm target joint state
    - names: 
      - left_arm_target_joint_1
      - left_arm_target_joint_2
      - left_arm_target_joint_3
      - left_arm_target_joint_4
      - left_arm_target_joint_5
      - left_arm_target_joint_6
      - left_arm_target_joint_7
      args:
        topic_name: /motion_target/target_joint_state_arm_left
        range_from: 0
        range_to: 7
      # messages: sensor_msgs/msg/JointState

    ### right arm target joint state
    - names: 
      - right_arm_target_joint_1
      - right_arm_target_joint_2
      - right_arm_target_joint_3
      - right_arm_target_joint_4
      - right_arm_target_joint_5
      - right_arm_target_joint_6
      - right_arm_target_joint_7
      args:
        topic_name: /motion_target/target_joint_state_arm_right
        range_from: 0
        range_to: 7
      # messages: sensor_msgs/msg/JointState

    ### left gripper target position
    - names: 
      - left_gripper_target_position
      args:
        topic_name: /motion_target/target_position_gripper_left
        range_from: 0
        range_to: 1
      # messages: sensor_msgs/msg/JointState

    ### right gripper target position
    - names: 
      - right_gripper_target_position
      args:
        topic_name: /motion_target/target_position_gripper_right
        range_from: 0
        range_to: 1
      # messages: sensor_msgs/msg/JointState

    ### torso target velocity
    - names:
      - torso_target_vel_x
      - torso_target_vel_y
      - torso_target_vel_z
      - torso_target_ang_vel_x
      - torso_target_ang_vel_y
      - torso_target_ang_vel_z
      args:
        topic_name: /motion_target/target_speed_torso
        range_from: 0
        range_to: 6
      # messages: geometry_msgs/msg/TwistStamped

    ### chassis target velocity
    - names:
      - chassis_target_vel_x
      - chassis_target_vel_y
      - chassis_target_vel_z
      - chassis_target_ang_vel_x
      - chassis_target_ang_vel_y
      - chassis_target_ang_vel_z
      args:
        topic_name: /motion_target/target_speed_chassis
        range_from: 0
        range_to: 6
      # messages: geometry_msgs/msg/TwistStamped
