# config.yml
pika:
  module: robocoin-dataset.scripts.dataset_statics.dataset_statics_collector_pika
  class: DatasetStaticsCollectorPika

unitree:
  module: robocoin-dataset.scripts.dataset_statics.dataset_statics_collector_unitree
  class: DatasetStaticsCollectorUnitree

hdf5:
  module: robocoin-dataset.scripts.dataset_statics.dataset_statics_collector_hdf5
  class: DatasetStaticsCollectorHdf5