### fps by manual
fps: 30
features:
  observation:
    images:

    ### values by manual
    - cam_name: cam
      args:

        ### key and values by manual
        h5_path: camera/color/Camera


      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.cam_high : by _gen_lerobot_features()
        

    # ### values by manual
    # - cam_name: cam_left_wrist_rgb
    #   args:

    #     ### keys and values by manual
    #     h5_path: observations/images/cam_left_wrist

    #   ### values by function
    #   # dtype: video
    #   # shape: [480, 640, 3]
    #   # names: [height, width, channels]
    #   # lerobot_feature: observations.images.cam_left_wrist : by _gen_lerobot_features()

    # ### values by manual
    # - cam_name: cam_right_wrist_rgb
    #   args:
    #     ### keys and values by manual
    #     h5_path: observations/images/cam_right_wrist

    #   ### values by function
    #   # dtype: video
    #   # shape: [480, 640, 3]
    #   # names: [height, width, channels]
    #   # lerobot_feature: observations.images.cam_right_wrist : by _gen_lerobot_features()


    state:
      ### values by function
      # lerobot_feature: observation.state : by _gen_lerobot_features()
      # dtype: float32 
      # shape: [16]

      ## sub_states should be concatenated together here : by _gen_state_names(), such as:
      # names: 
      # - right_joint_1_rad
      # - ...
      # - right_joint_7_rad
      # - ...


      ### values by manual
      sub_state:
      # 主机械臂关节位置 (7维)
      - names: 
        - master_joint_1_rad
        - master_joint_2_rad
        - master_joint_3_rad
        - master_joint_4_rad
        - master_joint_5_rad
        - master_joint_6_rad
        - master_joint_7_rad

        args:
          ### keys and values by manual
          h5_path: arm/jointStatePosition/master
          range_from: 0
          range_to: 7
        
        ### values by manual
        # convert_func: degree2rad

      # 从动机械臂关节位置 (7维)  
      - names: 
        - joint_1_rad
        - joint_2_rad
        - joint_3_rad
        - joint_4_rad
        - joint_5_rad
        - joint_6_rad
        - joint_7_rad

        args:
          ### keys and values by manual
          h5_path: arm/jointStatePosition/joint
          range_from: 0
          range_to: 7
        
        ### values by manual
        # convert_func: degree2rad

      # 单独关节位置 (7维)
      - names: 
        - joint_single_1_rad
        - joint_single_2_rad
        - joint_single_3_rad
        - joint_single_4_rad
        - joint_single_5_rad
        - joint_single_6_rad
        - joint_single_7_rad

        args:
          ### keys and values by manual
          h5_path: arm/jointStatePosition/joint_single
          range_from: 0
          range_to: 7
        
        ### values by manual
        # convert_func: degree2rad

      # 主机械臂末端姿态 (6维)
      - names: 
        - master_end_pos_x
        - master_end_pos_y
        - master_end_pos_z
        - master_end_rot_x
        - master_end_rot_y
        - master_end_rot_z

        args:
          ### keys and values by manual
          h5_path: arm/endPose/master
          range_from: 0
          range_to: 6
        
        ### values by manual
        # convert_func: degree2rad

      # 从动机械臂末端姿态 (6维)
      - names: 
        - puppet_end_pos_x
        - puppet_end_pos_y
        - puppet_end_pos_z
        - puppet_end_rot_x
        - puppet_end_rot_y
        - puppet_end_rot_z

        args:
          ### keys and values by manual
          h5_path: arm/endPose/puppet
          range_from: 0
          range_to: 6
        
        ### values by manual
        # convert_func: degree2rad

      # Pika机器人定位姿态 (6维)
      - names: 
        - pika_pos_x
        - pika_pos_y
        - pika_pos_z
        - pika_rot_x
        - pika_rot_y
        - pika_rot_z

        args:
          ### keys and values by manual
          h5_path: localization/pose/pika
          range_from: 0
          range_to: 6
        
        ### values by manual
        # convert_func: degree2rad
      
      # ### values by manual
      # - names: 
      #   - left_gripper_open_rad
      #   args:
      #     ### keys and values by manual
      #     h5_path: arm/jointStatePosition/joint
      #     range_from: 10
      #     range_to: 11

        ### values by manual
        # convert_func: degree2rad

      # ### values by manual
      # - names: 
      #   - left_pos_x
      #   - left_pos_y
      #   - left_pos_z
      #   - left_rot_x
      #   - left_rot_y
      #   - left_rot_z
      #   - left_rot_w

      #   args:
      #     ### keys and values by manual
      #     h5_path: observations/qpos
      #     range_from: 50
      #     range_to: 57

      #   ### values by manual
      #   # convert_func: degree2rad

      # ### values by manual
      # - names: 
      #   - right_gripper_open_rad
      #   args:
      #     ### keys and values by manual
      #     h5_path: observations/qpos
      #     range_from: 60
      #     range_to: 61

      #   ### values by manual
      #   # convert_func: degree2rad

  action:
    ### values by function
    # lerobot_feature: observation.action: by _gen_lerobot_features()
    # dtype: float32 
    # shape: [16]

    ## sub_actions should be concatenated together here, : by _gen_acton_names(), such as:
    # names:
    # - right_joint_1_rad
    # - ...
    # - right_joint_7_rad
    # - ...

    ### values by manual
    timeline_offset: 1
    sub_action:
    # 主机械臂关节位置作为动作 (7维)
    - names: 
      - master_joint_1_rad
      - master_joint_2_rad
      - master_joint_3_rad
      - master_joint_4_rad
      - master_joint_5_rad
      - master_joint_6_rad
      - master_joint_7_rad

      args:
        ### keys and values by manual
        h5_path: arm/jointStatePosition/master
        range_from: 0
        range_to: 7

    # 从动机械臂关节位置作为动作 (7维)  
    - names: 
      - joint_1_rad
      - joint_2_rad
      - joint_3_rad
      - joint_4_rad
      - joint_5_rad
      - joint_6_rad
      - joint_7_rad

      args:
        ### keys and values by manual
        h5_path: arm/jointStatePosition/joint
        range_from: 0
        range_to: 7

    # 主机械臂末端姿态作为动作 (6维)
    - names: 
      - master_end_pos_x
      - master_end_pos_y
      - master_end_pos_z
      - master_end_rot_x
      - master_end_rot_y
      - master_end_rot_z

      args:
        ### keys and values by manual
        h5_path: arm/endPose/master
        range_from: 0
        range_to: 6
    
    # ### values by manual
    # - names: 
    #   - left_gripper_open_rad
    #   args:
    #     ### keys and values by manual
    #     h5_path: observations/qpos
    #     range_from: 10
    #     range_to: 11

    # ### values by manual
    # - names: 
    #   - left_joint_1_rad
    #   - left_joint_2_rad
    #   - left_joint_3_rad
    #   - left_joint_4_rad
    #   - left_joint_5_rad
    #   - left_joint_6_rad
    #   - left_joint_7_rad
    #   args:
    #     ### keys and values by manual
    #     h5_path: observations/qpos
    #     range_from: 50
    #     range_to: 57

    # ### values by manual
    # - names: 
    #   - right_gripper_open_rad
    #   args:
    #     ### keys and values by manual
    #     h5_path: observations/qpos
    #     range_from: 60
    #     range_to: 61
    