### fps by manual
fps: 30
features:
  observation:
    images:

    ### values by manual
    - cam_name: color_head
      args:

        ### key and values by manual
        image_key: color_0


      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.color_head : by _gen_lerobot_features()


    state:
      ### values by function
      # lerobot_feature: observation.state : by _gen_lerobot_features()
      # dtype: float32 
      # shape: [28]

      ## sub_states should be concatenated together here : by _gen_state_names(), such as:
      # names: 
      # - left_arm_joint_1_rad
      # - ...
      # - left_arm_joint_7_rad
      # - ...


      ### values by manual
      sub_state:
      - names: 
        - left_arm_joint_1_rad
        - left_arm_joint_2_rad
        - left_arm_joint_3_rad
        - left_arm_joint_4_rad
        - left_arm_joint_5_rad
        - left_arm_joint_6_rad
        - left_arm_joint_7_rad

        args:
          ### keys and values by manual
          json_path: states.left_arm.qpos
          range_from: 0
          range_to: 7
        
        ### values by manual
        # convert_func: degree2rad
      
      ### values by manual
      - names: 
        - right_arm_joint_1_rad
        - right_arm_joint_2_rad
        - right_arm_joint_3_rad
        - right_arm_joint_4_rad
        - right_arm_joint_5_rad
        - right_arm_joint_6_rad
        - right_arm_joint_7_rad

        args:
          ### keys and values by manual
          json_path: states.right_arm.qpos
          range_from: 0
          range_to: 7

        ### values by manual
        # convert_func: degree2rad

      ### values by manual
      - names: 
        - left_hand_joint_1_rad
        - left_hand_joint_2_rad
        - left_hand_joint_3_rad
        - left_hand_joint_4_rad
        - left_hand_joint_5_rad
        - left_hand_joint_6_rad

        args:
          ### keys and values by manual
          json_path: states.left_hand.qpos
          range_from: 0
          range_to: 6

        ### values by manual
        # convert_func: degree2rad

      ### values by manual
      - names: 
        - right_hand_joint_1_rad
        - right_hand_joint_2_rad
        - right_hand_joint_3_rad
        - right_hand_joint_4_rad
        - right_hand_joint_5_rad
        - right_hand_joint_6_rad

        args:
          ### keys and values by manual
          json_path: states.right_hand.qpos
          range_from: 0
          range_to: 6

        ### values by manual
        # convert_func: degree2rad

  action:
    ### values by function
    # lerobot_feature: action: by _gen_lerobot_features()
    # dtype: float32 
    # shape: [28]

    ## sub_actions should be concatenated together here, : by _gen_acton_names(), such as:
    # names:
    # - left_arm_joint_1_rad
    # - ...
    # - left_arm_joint_7_rad
    # - ...

    ### values by manual
    timeline_offset: 1
    sub_action:
    - names: 
      - left_arm_joint_1_rad
      - left_arm_joint_2_rad
      - left_arm_joint_3_rad
      - left_arm_joint_4_rad
      - left_arm_joint_5_rad
      - left_arm_joint_6_rad
      - left_arm_joint_7_rad

      args:
        ### keys and values by manual
        json_path: actions.left_arm.qpos
        range_from: 0
        range_to: 7
    
    ### values by manual
    - names: 
      - right_arm_joint_1_rad
      - right_arm_joint_2_rad
      - right_arm_joint_3_rad
      - right_arm_joint_4_rad
      - right_arm_joint_5_rad
      - right_arm_joint_6_rad
      - right_arm_joint_7_rad

      args:
        ### keys and values by manual
        json_path: actions.right_arm.qpos
        range_from: 0
        range_to: 7

    ### values by manual
    - names: 
      - left_hand_joint_1_rad
      - left_hand_joint_2_rad
      - left_hand_joint_3_rad
      - left_hand_joint_4_rad
      - left_hand_joint_5_rad
      - left_hand_joint_6_rad

      args:
        ### keys and values by manual
        json_path: actions.left_hand.qpos
        range_from: 0
        range_to: 6

    ### values by manual
    - names: 
      - right_hand_joint_1_rad
      - right_hand_joint_2_rad
      - right_hand_joint_3_rad
      - right_hand_joint_4_rad
      - right_hand_joint_5_rad
      - right_hand_joint_6_rad

      args:
        ### keys and values by manual
        json_path: actions.right_hand.qpos
        range_from: 0
        range_to: 6
