realman_rmc_aidal: 
- version: default_version
  verison_description: two arms and two grippers, three rgb cameras with high, left wrist, right wrist
  module: robocoin_dataset.format_converter.tolerobot.lerobot_format_converter_h5
  class: LerobotFormatConverterHdf5
  converter_config_path: converter_config_realman_rmc_aidal.yaml

- version: test_version
  verison_description: two arms and two grippers, three rgb cameras with high, left wrist, right wrist
  module: robocoin_dataset.format_converter.tolerobot.lerobot_format_converter_h5
  class: LerobotFormatConverterHdf5
  converter_config_path: converter_config_realman_rmc_aidal.yaml