### fps by manual
fps: 30
features:
  observation:
    images:

    ### values by manual
    - cam_name: cam_high_rgb
      args:

        ### key and values by manual
        h5_path: observations/images/cam_high


      ### values by function
      # dtype: video
      # shape: [720, 1280, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.cam_high : by _gen_lerobot_features()
        

    ### values by manual
    - cam_name: cam_left_wrist_rgb
      args:

        ### keys and values by manual
        h5_path: observations/images/cam_left_wrist

      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.cam_left_wrist : by _gen_lerobot_features()

    ### values by manual
    - cam_name: cam_right_wrist_rgb
      args:
        ### keys and values by manual
        h5_path: observations/images/cam_right_wrist

      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.cam_right_wrist : by _gen_lerobot_features()

    ### values by manual
    - cam_name: cam_high_depth
      args:
        ### keys and values by manual
        h5_path: observations/depth/cam_high

      ### values by function
      # dtype: video
      # shape: [768, 1024, 1]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.cam_high_depth : by _gen_lerobot_features()


    state:
      ### values by function
      # lerobot_feature: observation.state : by _gen_lerobot_features()
      # dtype: float32 
      # shape: [128]

      ## sub_states should be concatenated together here : by _gen_state_names(), such as:
      # names: 
      # - joint_1
      # - ...
      # - joint_128


      ### values by manual
      sub_state:
      - names: 
        - qpos_1
        - qpos_2
        - qpos_3
        - qpos_4
        - qpos_5
        - qpos_6
        - qpos_7
        - qpos_8
        - qpos_9
        - qpos_10
        - qpos_11
        - qpos_12
        - qpos_13
        - qpos_14
        - qpos_15
        - qpos_16
        - qpos_17
        - qpos_18
        - qpos_19
        - qpos_20
        - qpos_21
        - qpos_22
        - qpos_23
        - qpos_24
        - qpos_25
        - qpos_26
        - qpos_27
        - qpos_28
        - qpos_29
        - qpos_30
        - qpos_31
        - qpos_32
        - qpos_33
        - qpos_34
        - qpos_35
        - qpos_36
        - qpos_37
        - qpos_38
        - qpos_39
        - qpos_40
        - qpos_41
        - qpos_42
        - qpos_43
        - qpos_44
        - qpos_45
        - qpos_46
        - qpos_47
        - qpos_48
        - qpos_49
        - qpos_50
        - qpos_51
        - qpos_52
        - qpos_53
        - qpos_54
        - qpos_55
        - qpos_56
        - qpos_57
        - qpos_58
        - qpos_59
        - qpos_60
        - qpos_61
        - qpos_62
        - qpos_63
        - qpos_64
        - qpos_65
        - qpos_66
        - qpos_67
        - qpos_68
        - qpos_69
        - qpos_70
        - qpos_71
        - qpos_72
        - qpos_73
        - qpos_74
        - qpos_75
        - qpos_76
        - qpos_77
        - qpos_78
        - qpos_79
        - qpos_80
        - qpos_81
        - qpos_82
        - qpos_83
        - qpos_84
        - qpos_85
        - qpos_86
        - qpos_87
        - qpos_88
        - qpos_89
        - qpos_90
        - qpos_91
        - qpos_92
        - qpos_93
        - qpos_94
        - qpos_95
        - qpos_96
        - qpos_97
        - qpos_98
        - qpos_99
        - qpos_100
        - qpos_101
        - qpos_102
        - qpos_103
        - qpos_104
        - qpos_105
        - qpos_106
        - qpos_107
        - qpos_108
        - qpos_109
        - qpos_110
        - qpos_111
        - qpos_112
        - qpos_113
        - qpos_114
        - qpos_115
        - qpos_116
        - qpos_117
        - qpos_118
        - qpos_119
        - qpos_120
        - qpos_121
        - qpos_122
        - qpos_123
        - qpos_124
        - qpos_125
        - qpos_126
        - qpos_127
        - qpos_128

        args:
          ### keys and values by manual
          h5_path: observations/qpos
          range_from: 0
          range_to: 128


  action:
    ### values by function
    # lerobot_feature: observation.action: by _gen_lerobot_features()
    # dtype: float32 
    # shape: [128]

    ## sub_actions should be concatenated together here, : by _gen_acton_names(), such as:
    # names:
    # - action_1
    # - ...
    # - action_128

    ### values by manual
    timeline_offset: 1
    sub_action:

      - names: 
        - action_1
        - action_2
        - action_3
        - action_4
        - action_5
        - action_6
        - action_7
        - action_8
        - action_9
        - action_10
        - action_11
        - action_12
        - action_13
        - action_14
        - action_15
        - action_16
        - action_17
        - action_18
        - action_19
        - action_20
        - action_21
        - action_22
        - action_23
        - action_24
        - action_25
        - action_26
        - action_27
        - action_28
        - action_29
        - action_30
        - action_31
        - action_32
        - action_33
        - action_34
        - action_35
        - action_36
        - action_37
        - action_38
        - action_39
        - action_40
        - action_41
        - action_42
        - action_43
        - action_44
        - action_45
        - action_46
        - action_47
        - action_48
        - action_49
        - action_50
        - action_51
        - action_52
        - action_53
        - action_54
        - action_55
        - action_56
        - action_57
        - action_58
        - action_59
        - action_60
        - action_61
        - action_62
        - action_63
        - action_64
        - action_65
        - action_66
        - action_67
        - action_68
        - action_69
        - action_70
        - action_71
        - action_72
        - action_73
        - action_74
        - action_75
        - action_76
        - action_77
        - action_78
        - action_79
        - action_80
        - action_81
        - action_82
        - action_83
        - action_84
        - action_85
        - action_86
        - action_87
        - action_88
        - action_89
        - action_90
        - action_91
        - action_92
        - action_93
        - action_94
        - action_95
        - action_96
        - action_97
        - action_98
        - action_99
        - action_100
        - action_101
        - action_102
        - action_103
        - action_104
        - action_105
        - action_106
        - action_107
        - action_108
        - action_109
        - action_110
        - action_111
        - action_112
        - action_113
        - action_114
        - action_115
        - action_116
        - action_117
        - action_118
        - action_119
        - action_120
        - action_121
        - action_122
        - action_123
        - action_124
        - action_125
        - action_126
        - action_127
        - action_128

        args:
          ### keys and values by manual
          h5_path: action
          range_from: 0
          range_to: 128
